version: 2
jobs:
  build:
    working_directory: ~/buildnotify
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          command: |
            apt-get update
            apt-get install -y -qq python-pyqt5 python-keyring xvfb curl git
            curl -s https://bootstrap.pypa.io/get-pip.py | python
            pip install tox
            xvfb-run --server-args="-screen 0 1024x768x24" tox -ecoveralls
